[ADD] New messages after Openforce dinner
openforceit/orco-bot-old pull request #3
Opened 2020-07-29 15:26 UTC by OpenCode

2020-07-29 15:28 UTC, matteoopenf approved these changes

2020-08-17 10:25 UTC, warp10 requested changes

2020-08-17 10:25 UTC, warp10 commented on src/orco_bot/config.py
> +    "Is this a PR? Frechte!!!",
Non ci siamo: è "Freechete". Ma <3 per l'idea :*

2020-12-17 09:08 UTC, OpenCode commented on src/orco_bot/config.py
> +    "Is this a PR? Frechte!!!",
Fatto

2020-12-17 09:10 UTC, SilvioGregorini approved these changes

2020-12-17 10:18 UTC, merged